#!/bin/bash -l

# ==== ONLY EDIT WITHIN THIS BLOCK =====

# Replace DASK_DASHBOARD_URL with the proxy location
sed -i -e "s|DASK_DASHBOARD_URL|${JUPYTERHUB_BASE_URL}user/${JUPYTERHUB_USER}/proxy/8787|g" /srv/jupyterlab-workspace.json

# Set the workspace config
export JUPYTERLAB_WORKSPACES_DIR=srv/jupyterlab-workspaces
jupyter lab workspaces import /srv/jupyterlab-workspace.json

# ==== ONLY EDIT WITHIN THIS BLOCK =====

exec "$@"
